[build]
  # When deployed on Netlify, run Tailwind CSS v3 CLI to generate the static optimized CSS file
  command = "npx tailwindcss@3 -i ./input.css -o ./output.css --minify"
  # Publish the entire directory
  publish = "."

[[headers]]
  # Basic security headers for Netlify
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
