[build]
  # When deployed on Netlify, run Tailwind CSS CLI to generate the static optimized CSS file
  command = "npm install -D tailwindcss && npx tailwindcss -i ./input.css -o ./output.css --minify"
  # Publish the entire directory
  publish = "."

[[headers]]
  # Basic security headers for Netlify
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
